### ISSUE TITLE
export from RodeRunner

### ISSUE THREAD

**Issue by FBanani** [ar4development/carla_build#1]
Hi
Thank you so much for your great tutorial. 
I have some issues could you help me?
When I want to use the map for Carla should I export the file to Carla or unreal engine?
From your guide in YouTube, I understand I have to export to Unreal engine is it true?
if yes, I saw the following warning! 
![9c9f9109-49fe-4e04-b679-ac6e132c0e76](https://user-images.githubusercontent.com/98695913/208969593-7019f807-7b16-486f-a8b1-807cc02bc33f.jpg)
and the export files is like as follows:
![cb977e6a-c90f-4c80-b11c-3e014aac1b28](https://user-images.githubusercontent.com/98695913/208969766-9f0da45c-b75a-4eef-99bb-c8d416959d9f.jpg)
The steps that I do is as follows:
then I import the unreal engine in this way:
1:
![60e590c8-30e9-4ec1-bf82-223426a52ca5](https://user-images.githubusercontent.com/98695913/208971507-ee1cb247-cc62-41f9-9679-b92c70ea7607.jpg)
2:
![f5ca20e0-4cb3-4560-9213-44bd08b42e62](https://user-images.githubusercontent.com/98695913/208971731-68627ccb-c622-4eb8-a529-bfc57f2cbfac.jpg)
In this step should I select all of them?
After that, I press the "import all" button as follows:
![5964d549-a15d-4fd1-9995-c16e4dac0f4f](https://user-images.githubusercontent.com/98695913/208972157-5db839b4-7138-4862-b02c-0536a5d9cff0.jpg)
Therefore, it shows me this message and does not add the new map to the unreal engine! as you can see in the following.
![ef814161-214d-48ea-b143-72e00f5043b2](https://user-images.githubusercontent.com/98695913/209176953-4b2e425a-179c-4469-b44f-3990805939f8.jpg)
Could you help me? 

Regards

**Comment by ar4development** [comment]
Hi @FBanani 

I'm really sorry for such a late answer. But better later than never :). When you import maps from RoadRunner you should install RoadRunner plugin to your Carla UE4. Thus it takes care of all the stuff. The plugin should come with RoadRunner distribution.

**Comment by FBanani** [comment]
> Hi @FBanani
> 
> I'm really sorry for such a late answer. But better later than never :). When you import maps from RoadRunner you should install RoadRunner plugin to your Carla UE4. Thus it takes care of all the stuff. The plugin should come with RoadRunner distribution.

Thank you so much. I installed it, but because my map is not complete it does not show.
I have another question is there any document for changing walkers' clothes in Carla? I want to customize their clothes to create workers.

**Comment by ar4development** [comment]
@FBanani honestly I do not have an experience of doing that. Yet I only know how to customize trucks. But I believe with pedestrians the things are pretty much the same (and for your particular task is even easier). Just copy-paste the whole stuff for some existing pedestrian class (models, physics, all kind of blue-prints) and change the textures. But probably if you need some more realistic (like special sort of outfit or road-worker tools) I think the things are getting harder.
